from __future__ import annotations

from pathlib import Path

from .models import NetworkCase


def write_dss(case: NetworkCase, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{case.name}.dss"
    lines: list[str] = [
        f"! Generated by DNR for {case.title}",
        "Clear",
        f"New Circuit.{case.name} bus1={case.slack_bus} basekv={case.base_kv} pu=1.0 phases=3",
        "",
    ]
    for branch in case.branches:
        r0 = branch.r0_ohm if branch.r0_ohm is not None else max(branch.r_ohm * 3.0, branch.r_ohm)
        x0 = branch.x0_ohm if branch.x0_ohm is not None else max(branch.x_ohm * 3.0, branch.x_ohm)
        lines.append(
            "New Line.L{idx} phases=3 bus1={f} bus2={t} "
            "r1={r:.10g} x1={x:.10g} r0={r0:.10g} x0={x0:.10g} "
            "c1=0 c0=0 length={length:.10g} units=km".format(
                idx=branch.idx,
                f=branch.from_bus,
                t=branch.to_bus,
                r=branch.r_ohm,
                x=branch.x_ohm,
                r0=r0,
                x0=x0,
                length=max(branch.length_km, 1e-6),
            )
        )
    lines.append("")
    for bus in case.buses:
        if bus.idx == case.slack_bus or (bus.pd_kw == 0 and bus.qd_kvar == 0):
            continue
        lines.append(
            f"New Load.Load{bus.idx} bus1={bus.idx} phases=3 conn=wye "
            f"kv={case.base_kv} kw={bus.pd_kw:.10g} kvar={bus.qd_kvar:.10g} model=1"
        )
    lines.extend(
        [
            "",
            f"Set VoltageBases=[{case.base_kv}]",
            "CalcVoltageBases",
            "Set MaxIterations=100",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


class OpenDssRunner:
    def __init__(self, dss_path: Path):
        try:
            import opendssdirect as dss
        except ImportError as exc:
            raise RuntimeError(
                "Falta opendssdirect.py. Active el ambiente DNR e instale dependencias."
            ) from exc
        self.dss = dss
        self.dss_path = dss_path

    def solve(self, open_switches: list[int] | tuple[int, ...]) -> dict[str, float | bool]:
        dss = self.dss
        dss.Basic.ClearAll()
        dss.Text.Command(f'Compile "{self.dss_path}"')
        for switch in open_switches:
            dss.Text.Command(f"Disable Line.L{int(switch)}")
        dss.Text.Command("Solve")
        converged = bool(dss.Solution.Converged())
        losses = dss.Circuit.Losses()
        voltages = dss.Circuit.AllBusMagPu()
        min_voltage = min(voltages) if voltages else None
        max_voltage = max(voltages) if voltages else None
        return {
            "converged": converged,
            "losses_kw": float(losses[0]) / 1000.0 if losses else None,
            "min_voltage_pu": float(min_voltage) if min_voltage is not None else None,
            "max_voltage_pu": float(max_voltage) if max_voltage is not None else None,
        }
